---
- name: Create traefik docker network
  docker_network:
    name: "{{ traefik_docker_network }}"
    state: present

- name: Start traefik
  docker_compose:
    state: present
    project_src: "{{ traefik_directory }}"
