---
- include: guard.yml

- include: install.yml

- include: install-network.yml

- include: configure.yml

- include_tasks: configure-compose.yml
  when: not traefik_use_swarm

- include_tasks: configure-swarm.yml
  when: traefik_use_swarm
