---
- include: install.yml

- include: configure.yml

- include_tasks: configure-compose.yml
  when: not traefik_use_swarm

- name: Swarm Setup
  block:
    - name: Create traefik docker network (Swarm)
      docker_network:
        name: "{{ traefik_docker_network }}"
        state: present
        attachable: "{{ traefik_swarm_network_attachable | bool }}"
        driver: "{{ traefik_swarm_network_driver }}"

    - include_tasks: configure-swarm.yml
  when: traefik_use_swarm
