---
- name: "guard"
  ansible.builtin.include_tasks: guard.yml

- name: "install"
  ansible.builtin.include_tasks: install.yml

- name: "install network"
  ansible.builtin.include_tasks: install-network.yml

- name: "configure traefik"
  ansible.builtin.include_tasks: configure.yml

- name: "deploy with docker-compose"
  ansible.builtin.include_tasks: configure-compose.yml
  when: not traefik_use_swarm

- name: "deploy with docker swarm"
  ansible.builtin.include_tasks: configure-swarm.yml
  when: traefik_use_swarm
