---
dependency:
  name: galaxy
driver:
  name: hetznercloud
lint:
  name: yamllint
platforms:
  - name: ansible-traefik-docker-test-${CIRCLE_BUILD_NUM:-111}
    server_type: cx21
    image: centos-7
provisioner:
  name: ansible
  options:
    diff: false
    v: true
  lint:
    name: ansible-lint
scenario:
  name: swarm
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
