---
- name: Converge
  hosts: all
  roles:
    - role: ansible_traefik_docker
      vars:
        traefik_version: "v1.7"
        traefik_use_swarm: true
        traefik_swarm_mode: true
        traefik_consul_enable: true
        traefik_consul_endpoint: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8500"
        traefik_compose_version: 3.2
        traefik_docker_network: "traefik"
        traefik_docker_domain: 'traefik-swarm.docker.local'
        traefik_acme_enable: false
        traefik_dashboard_basicauth_enable: false
  pre_tasks:
    - name: Install wget
      yum:
        name:
          - wget
  tasks:
    - name: Get docker networks
      command: docker network ls
      register: __networks
    - name: Show networks
      debug:
        var: __networks.stdout_lines
    - name: start test web server
      docker_swarm_service:
        name: testhttp
        image: deis/example-go
        networks:
          - "{{ traefik_docker_network }}"
        labels:
          test: webserver
          traefik.enable: "true"
          traefik.port: "8080"
          traefik.docker.network: "{{ traefik_docker_network }}"
    - name: Restart traefik
      command:
        cmd: docker service update --force traefik_traefik
    - name: Try connection
      command:
        argv:
          - wget
          - --no-check-certificate
          - --header="Host:traefik.traefik-swarm.docker.local"
          - https://127.0.0.1:443/api/providers/docker
      ignore_errors: true
      register: wget_test
      failed_when: false
      tags:
        - skip_ansible_lint
    # - name: Try connecting
    #   command:
    #     argv:
    #       - curl
    #       - --tlsv1.1
    #       - --location
    #       - --insecure
    #       - --verbose
    #       - --silent
    #       - -H "Host:traefik.traefik-swarm.docker.local"
    #       - https://127.0.0.1:443/api/providers/docker
    #   ignore_errors: true
    #   register: curl_test
    - name: Show output
      debug:
        var: wget_test
    - name: Restart traefik
      command:
        cmd: docker service update --force traefik_traefik
    - name: Wait for traefik to come up
      wait_for:
        port: 80
