---
- name: Converge
  hosts: all
  roles:
    - role: ansible-traefik-docker
  tasks:
    - name: Get docker networks
      command: docker network ls
      register: __networks
    - name: Show networks
      debug:
        var: __networks.stdout_lines
    - name: start test web server
      docker_swarm_service:
        name: testhttp
        image: deis/example-go
        networks:
          - "{{ traefik_docker_network }}"
        labels:
          test: webserver
          traefik.enable: "true"
          traefik.port: "8080"
          traefik.docker.network: "{{ traefik_docker_network }}"
    - name: Wait for traefik/consul to come up
      wait_for:
        port: 80
    - name: Restart traefik
      command:
        cmd: docker service update --force traefik_traefik
    - name: Try connecting
      command:
        cmd: curl -L -k -v -s -H "Host:traefik.traefik-swarm.docker.local" https://127.0.0.1:443/api/providers/docker
      ignore_errors: true
      failed_when: false
      tags:
        - skip_ansible_lint
    - name: Restart traefik
      command:
        cmd: docker service update --force traefik_traefik
    - name: Wait for traefik/consul to come up
      wait_for:
        port: 80
  vars:
    traefik_version: "v1.7"
    traefik_use_swarm: true
    traefik_swarm_mode: true
    traefik_consul_enable: true
    traefik_consul_placement: 'node.platform.os == linux'
    traefik_compose_version: 3.2
    traefik_docker_network: "traefik"
    traefik_docker_domain: 'traefik-swarm.docker.local'
    traefik_acme_enable: false
    traefik_dashboard_basicauth_enable: false
