name: pr

on: pull_request

jobs:
  build:
    env:
      DOCKER_IMAGE: "molecule-test:latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: mkdir -p /home/runner/.cache/pip
      if: ${{ !env.ACT }}
    - run: mkdir -p /root/.cache/pip
      if: env.ACT
    - uses: actions/setup-python@v5
      with:
        python-version: '3.7.17'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ansible-lint ./
