name: pr

on: pull_request

jobs:
  build:
    env:
      DOCKER_IMAGE: "molecule-test:latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: mkdir -p /root/.cache/pip
    - uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: '3.7.17'
        cache: 'pip'
    - run: ansible-lint ./
